### ISSUE TITLE
[windows][question] Binary path on Windows

### ISSUE THREAD

**Issue by kittaakos** [roblourens/vscode-ripgrep#10]
As I see, currently, the binary path cannot be consumed as is on Windows because it does not have the `.exe` file extension suffix.

See: https://github.com/roblourens/vscode-ripgrep/blob/9312d44db97db3e0873a40c6f51dc2c42796cb87/lib/index.js#L5

Of course, one can check the underlying operating system, and add the `.exe` if Windows, but shouldn't it be the responsibility of the library?

It works flawlessly on OS X and Linux, but not on Windows.

<img width="282" alt="screen shot 2018-03-27 at 09 04 53" src="https://user-images.githubusercontent.com/1405703/37955331-9eaceb1e-31a8-11e8-8cfd-2e5ec56e96df.png">

**Comment by roblourens** [comment]
Spawning it works for me on windows. But adding the .exe would be better. PR welcome

**Comment by kittaakos** [comment]
Cool, I'll take care of it. Thanks!

**Comment by kittaakos** [comment]
PR: https://github.com/roblourens/vscode-ripgrep/pull/12
