### ISSUE TITLE
Fail to install version 1.1.0

### ISSUE THREAD

**Issue by jamesjieye** [roblourens/vscode-ripgrep#15]
I used the following commands to install vscode-ripgrep and got an error.

```
git clone https://github.com/roblourens/vscode-ripgrep.git
cd vscode-ripgrep
npm install
```

And here is the error:

```
ThalesPro:vscode-ripgrep james$ npm install

> vscode-ripgrep@1.1.0 postinstall /Users/james/Workspace/OpenSource/vscode-ripgrep
> node ./lib/postinstall.js

Unzipping to /Users/james/Workspace/OpenSource/vscode-ripgrep/bin
Downloading ripgrep failed: Error: end of central directory record signature not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-ripgrep@1.1.0 postinstall: `node ./lib/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-ripgrep@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/james/.npm/_logs/2018-09-06T02_26_12_694Z-debug.log
```

Any advice? Thank you!

**Comment by roblourens** [comment]
Corrupt download? Delete and try again? It works in vscode.

**Comment by roblourens** [comment]
What platform?

**Comment by msuhail** [comment]
Encountered the same while installing theia on an ubuntu machine

**Comment by jamesjieye** [comment]
@roblourens I'm using macOS 10.13.6,  npm 5.6.0, also tried yarn 1.9.4, same result. 

I deleted the node_modules and also cleared yarn cache. And I verified npm's cache using `npm cache verify`.

@msuhail Me too. I encountered this while installing Theia.

**Comment by roblourens** [comment]
Sorry did you ever get it worked out?

**Comment by jamesjieye** [comment]
Close it since no longer reproducible.

**Comment by shrinktofit** [comment]
For someone who encounter the same error on Windows, you could remove all `~\AppData\Local\Temp\vscode-repgrep-cache*` folders and try again.
