### ISSUE TITLE
Downloading ripgrep failed: Error: No asset named ripgrep-0.10.0-pcre-linux-arm.zip

### ISSUE THREAD

**Issue by andlo** [roblourens/vscode-ripgrep#18]
Trying to install vscode-ripgrep on raspbian strech, but get this error
Downloading ripgrep failed: Error: No asset named ripgrep-0.10.0-pcre-linux-arm.zip

It seems like the install cant find the right file to download or something.

```
pi@picroft:~/test $ yarn add vscode-ripgrep
yarn add v1.12.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/pi/test/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: /home/pi/test/node_modules/vscode-ripgrep
Output:
Downloading ripgrep failed: Error: No asset named ripgrep-0.10.0-pcre-linux-arm.zip found
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
What can I do to fix this ?

**Comment by roblourens** [comment]
I just fixed the name on that release, please try again.

**Comment by andlo** [comment]
GREEEAT it  works :)
I didnt get any sleep last night because of this ;)

**Comment by roblourens** [comment]
Sorry, I'm not sure why the name ended up wrong :(

Btw, the ARM release is not "official" in that I don't test it and it doesn't run on an officially supported vscode platform. I just build it for the convenience of people who request it.
