### ISSUE TITLE
ripgrep does not always respect rules in .gitignore

### ISSUE THREAD

**Issue by elaihau** [roblourens/vscode-ripgrep#23]
Version of ripgrep: 1.2.4
OS: Ubuntu 16.04 64 bit
Problem: ripgrep does not always respect rules defined in .gitignore
Demo:
![peek 2019-02-25 15-17](https://user-images.githubusercontent.com/37082801/53365989-8713ea00-3910-11e9-8fc8-4aae3298016c.gif)

From my understanding of the help doc, ripgrep should be able to find rules defined in .gitignore files, and apply the rules when performs the search. Or maybe I wasn't running the command in the right way?

Thank you in advance.

**Comment by roblourens** [comment]
You want https://github.com/BurntSushi/ripgrep
