### ISSUE TITLE
install silently hangs when there is no Invoke-Webrequest cmdlet

### ISSUE THREAD

**Issue by Vineg** [roblourens/vscode-ripgrep#27]
Last log message is
>Downloading with Invoke-WebRequest

**Comment by roblourens** [comment]
Why is there no Invoke-WebRequest? What version of Windows are you on?

Also just out of curiosity, what are you using vscode-ripgrep for?

**Comment by Vineg** [comment]
I am on Windows 7 SP 1. It has preinstalled PowerShell 1.0.
This package is in dependency tree of theia ide (@theia/file-search -> vscode-ripgrep).

This is probably pretty rear issue and I solved it by upgrading Windows Management Framework to the current version. Still I am surprised that install pipeline didn't crash at least with some sort of error.

**Comment by roblourens** [comment]
Well it should handle errors from the 'exec', so it must be that powershell/windows was hanging. Glad you were able to resolve it. I don't think there's anything else I can fall back on.
