### ISSUE TITLE
Malware present in ia32 windows artifact

### ISSUE THREAD

**Issue by bryphe** [roblourens/vscode-ripgrep#6]
Hi @roblourens ,

It appears that the Windows ia32 artifact in the latest release is infected with malware:
https://github.com/roblourens/ripgrep/releases/download/0.6.0-patch.0/ripgrep-0.6.0-patch.0-win32-ia32.zip

One of my users reported this issue here: https://github.com/onivim/oni/issues/889

```
C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-ripgrep\bin\rg.exe
```

https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Mal~EncPk-ZC/detailed-analysis.aspx

At first I suspected it was being introduced on the build server (https://github.com/appveyor/ci/issues/1913), but then I isolated it to that particular release dependency.

The good news is that it does not seem VSCode is impacted, but wanted to give you a heads up.

Would it be possible to create a new release, or clean and refresh that particular artifact?

Thanks!

**Comment by roblourens** [comment]
Can you please check whether the vscode Insiders build has this issue? code.visualstudio.com/insiders

How can I verify this myself? It has never triggered windows defender as far as I know.

**Comment by bryphe** [comment]
Hi @roblourens ,

Thanks for the response! I used Sophos: https://home.sophos.com/ and was able to see a flag consistently for that particular artifact:

![image](https://user-images.githubusercontent.com/13532591/32562538-c7a3d706-c463-11e7-8656-690bc33a611c.png)

There is a chance that it is a false positive, but given that the ripgrep binaries available at https://github.com/BurntSushi/ripgrep/releases don't show the issue, it's a bit concerning.

> Can you please check whether the vscode Insiders build has this issue? code.visualstudio.com/insiders

I scanned the `ia32` zip for the insiders and there weren't any issues.

**Comment by roblourens** [comment]
>I scanned the ia32 zip for the insiders and there weren't any issues.

Thanks for trying that, because we're about to ship it to stable :)

The vscode build simply downloads the zip from that exact github release, so it doesn't make sense that one would contain malware and one wouldn't.

I downloaded this and scanned it with windows defender, and it didn't show any issues. It also appears to still be the same as the exe I originally uploaded and built on my own VM.

**Comment by roblourens** [comment]
Can you tell me how to get the details of the virus scan from a chrome download? Or how to bypass it and download the file anyway. It says "virus scan failed" but I don't see any details in Sophos.

**Comment by bryphe** [comment]
Thanks for investigating this, @roblourens !

It's interesting that Windows Defender doesn't show any hits - it's possible it's a false positive but I figured better to err on the safe side...

After the virus scan failed, I opened the Sophos app, and there is a notification icon in the top right:
![image](https://user-images.githubusercontent.com/13532591/32570413-e952a854-c478-11e7-9374-1b4a9b4751fa.png)

That showed me details for each of the violations (the specific malware it detected + a link to information about it).

**Comment by roblourens** [comment]
Hm, I actually don't get that notification.

Anyway, I am assuming this must be a false positive. We've had some issues with Windows Defender and other AV programs incorrectly flagging other files in vscode, and I don't have a good reason to believe that there's anything wrong with rg.exe here. Hopefully Sophos can detect this issue somehow.

We shipped VS Code with this rg.exe version to a lot of people today, so I hope I'm right :)

**Comment by roblourens** [comment]
And I'm just now getting other comments about the 32-bit rg.exe. Maybe I should just try rebuilding it. 

https://github.com/Microsoft/vscode/issues/37863#issuecomment-343050229

**Comment by bryphe** [comment]
Wow, just checked out the thread, that is bizarre! Maybe some sort of corruption that gets inadvertently picked up as malware. Rebuilding sounds good.

Congrats on the release!

**Comment by wodin** [comment]
FYI - https://www.virustotal.com/#/file-analysis/MjU0ZDUwM2U1M2Q0YTk5Mjc2MGE3NTViNzEzZjRlODU6MTUxMDU2MTMyOQ==

Cylance - Unsafe
Sophos AV - Mal/EncPk-ZC

All others detect no problems.
