### ISSUE TITLE
Wrong version?

### ISSUE THREAD

**Issue by Gruntfuggly** [roblourens/vscode-ripgrep#9]
Hi there

I may be using this wrong, but I have included vscode-ripgrep as part of an extension to vscode. When the extension is installed, it seems to include the vscode-ripgrep module in node_modules, but under windows it seems to be the wrong executable - I see bin/rg instead of bin/rg.exe?

If I manually uninstall vscode-ripgrep with npm and then reinstall it, I end up with the expected rg.exe. Actually - just installing it again once the extension has been installed seems to fix it.

It seems to work happily on my mac.

Is there something else I need to do?

**Comment by roblourens** [comment]
It downloads the binary during npm install, not when installing the extension. So you will probably need a different solution to use this cross-platform in an extension.

**Comment by Gruntfuggly** [comment]
OK, thanks.
